[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/percona/pmm"
  branch = "PMM-2.0"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.5.0"
